name: Python application test with Github Actions
on : [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make -C scaffold install
    - name: Lint with Pylint
      run: |
        make -C scaffold lint
    - name: Test with Pytest
      run: |
        make -C scaffold test
    - name: Format code with Python black
      run: |
        make -C scaffold format
